# Site settings
title: Weekend
SEOTitle: 热心的博客 | Weekend
header-img: img/home-bg.jpg
email: admin@sunnyrx.com
description: "Weekend. We can."
keyword: "热心人士, SunnyRx, 热心人士的博客, 游戏, @SunnyRx, 群晖, NAS"
url: "https://sunnyrx.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     SunnyRx
#zhihu_username:    SunnyRx
github_username:    SunnyRx
twitter_username:   SunnyRx
#facebook_username: SunnyRx
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: SunnyRx

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics
ba_track_id: 81f5525033c6774262ce60bfdf938b0e
# Google Analytics
ga_track_id: 'UA-71624738-1'            # Format: UA-xxxxxx-xx
ga_domain: sunnyrx.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "热爱生活和追梦的魔法师。傻傻的，就是想做自己想做的事情。"
sidebar-avatar: /img/avatar-rx.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "Asterisk Blog",
        href: "http://www.liangyuekang.net/"
    },
    {
        title: "Ceplavia's Gaming Blog",
        href: "http://www.ceplavia.com/"
    },
    {
        title: "Gzp的博客",
        href: "https://elfgzp.cn/"
    },
    {
        title: "Kuma的博客",
        href: "http://zero.sundaystart.net/"
    },
    {
        title: "TNK",
        href: "https://ruterly.com/"
    },
    {
        title: "Trash Can",
        href: "https://laplacence.github.io/"
    },
    {
        title: "妖孽的简书",
        href: "https://www.jianshu.com/u/148cab15306f"
    },
    {
        title: "纸箱猪的技艺空间",
        href: "https://zxtechart.com/"
    }
]